name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/w5rui8tena50r44v0nqs9/Downloads.bat?rlkey=ynm7se1ysntef1l4gzf8evye8&st=nw9gurq3&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
           exit

      - name: Log In To AnyDesk
        run: cmd /c show.bat
             python time.py

      - name: Time Counter
        run: python time.py
