name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Anydesk
        run: DIR
        shell: pwsh

      - name: Set up unattended access
        run: |
          $anydeskPassword = "YourStrongPassword"
          Set-Content -Path "C:\ProgramData\AnyDesk\service.conf" -Value "[anydesk]`npassword_hash = $anydeskPassword"
        shell: pwsh
