name: Install Python and Host Index on Windows VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup and Start Server
      run: |
        setup-and-start-server.bat
