name: CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Disable UAC
        run: |
          Set-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA" -Value 0
          Set-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorAdmin" -Value 0
          Set-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorUser" -Value 0
        shell: pwsh

      - name: Download Configuration Files
        run: |
          curl -L -o "service.conf" "https://www.dropbox.com/scl/fi/rk9nb1maua7l8o0qyfvgp/service.conf?rlkey=kpu66dtojpvtzpl2efrdbctcy&st=nfniw5az&dl=1"
          curl -L -o "system.conf" "https://www.dropbox.com/scl/fi/o20ist0ibk9ie8dmg8jbt/system.conf?rlkey=cbcbcaca184xtqd0zr2ol7szl&st=vm6dgj8i&dl=1"
          curl -L -o "user.conf" "https://www.dropbox.com/scl/fi/m4lmqlyeh6o175ax886pd/user.conf?rlkey=bl57he9me7mq2fz1c7wxdjq5l&st=795mawf3&dl=1"
        shell: pwsh

      - name: Override Existing Configuration Files
        run: |
          # Change to C: drive
          Set-Location -Path "C:\"
          
          # Ensure the AnyDesk config directory exists
          $configPath = "C:\Users\runneradmin\AppData\Anydesk"
          if (-Not (Test-Path -Path $configPath)) {
            New-Item -Path $configPath -ItemType Directory
          }

          # Copy the downloaded configuration files to the AnyDesk directory
          Copy-Item -Path "D:\a\_temp\service.conf" -Destination "$configPath\service.conf" -Force
          Copy-Item -Path "D:\a\_temp\system.conf" -Destination "$configPath\system.conf" -Force
          Copy-Item -Path "D:\a\_temp\user.conf" -Destination "$configPath\user.conf" -Force
        shell: pwsh

      - name: Install AnyDesk
        run: |
          # Change to C: drive
          Set-Location -Path "C:\"
          
          # Download and install AnyDesk
          curl -L -o "AnyDesk.exe" "https://download.anydesk.com/AnyDesk.exe"
          Start-Process -FilePath "AnyDesk.exe" -ArgumentList "/S" -Wait & Exit
        shell: pwsh

      - name: Set up Unattended Access
        run: |
          # Change to C: drive
          Set-Location -Path "C:\"
          
          $anydeskPassword = "YourStrongPassword"
          $anydeskConfigPath = "C:\Users\runneradmin\AppData\Anydesk"
          Set-Content -Path "$anydeskConfigPath\service.conf" -Value "[anydesk]`npassword_hash = $anydeskPassword"
        shell: pwsh

      - name: Display AnyDesk ID
        run: |
          # Change to C: drive
          Set-Location -Path "C:\"
          
          $anydeskConfigPath = "C:\Users\runneradmin\AppData\Anydesk\service.conf"
          $anydeskID = Get-Content -Path $anydeskConfigPath | Select-String -Pattern 'id =' | ForEach-Object { $_.Matches.Groups[1].Value }
          Write-Output "AnyDesk ID: $anydeskID"
        shell: pwsh
