name: Set Up RDP Access

on: [push]

jobs:
  setup-rdp:
    runs-on: windows-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Enable Remote Desktop
      run: |
        # Enable Remote Desktop by modifying the registry
        $regPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server"
        Set-ItemProperty -Path $regPath -Name "fDenyTSConnections" -Value 0

        # Allow Remote Desktop through the firewall
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Set User Credentials
        $username = "runneradmin"
        $password = "Tap71009"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force

        # Check if the user exists
        if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
          # Create the user if it does not exist
          net user $username $password /add
        }

        # Ensure the user is added to the Administrators group
        if (-not (Get-LocalGroupMember -Group "Administrators" -Member $username -ErrorAction SilentlyContinue)) {
          net localgroup administrators $username /add
        }

    - name: Get VM IP Address
      run: |
        $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.PrefixLength -eq 24}).IPAddress
        Write-Output "VM IP Address: $ip"
        
        # Save IP Address as an artifact
        Set-Content -Path vm_ip.txt -Value $ip

    - name: Upload IP Address
      uses: actions/upload-artifact@v3
      with:
        name: vm-ip-address
        path: vm_ip.txt
