name: Setup and Run Node.js Server on Windows VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: Kopp56-PRO/cloud-vm
        path: cloud-vm

    - name: Run ipconfig
      run: |
        ipconfig

    - name: Install Node.js
      shell: pwsh
      run: |
        # Navigate to the cloned repository directory
        Set-Location -Path "cloud-vm"

        # Define the Node.js installer URL
        $nodeInstallerUrl = "https://nodejs.org/dist/v18.17.1/node-v18.17.1-x64.msi"
        $nodeInstaller = "nodejs-installer.msi"

        # Download Node.js installer
        Invoke-WebRequest -Uri $nodeInstallerUrl -OutFile $nodeInstaller

        # Install Node.js
        Start-Process -Wait -FilePath msiexec -ArgumentList "/i $nodeInstaller /quiet /norestart"

        # Verify Node.js installation
        node --version
        npm --version

        # Clean up
        Remove-Item -Path $nodeInstaller

    - name: Run Server
      shell: pwsh
      run: |
        # Navigate to the cloned repository directory
        Set-Location -Path "cloud-vm"

        # Check if Node.js is installed
        if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
            Write-Output "Node.js is not installed. Installing Node.js..."
            $nodeInstallerUrl = "https://nodejs.org/dist/v18.17.1/node-v18.17.1-x64.msi"
            $nodeInstaller = "nodejs-installer.msi"
            Invoke-WebRequest -Uri $nodeInstallerUrl -OutFile $nodeInstaller
            Start-Process -Wait -FilePath msiexec -ArgumentList "/i $nodeInstaller /quiet /norestart"
        }

        # Run the Node.js server
        node server.js
