name: Kopp56's RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: K56 DEV's RDP
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In
        run: cmd /c show.bat

      - name: Keep running
        run: python time.py
